on:
  release:
    types: [published]

name: Discord Release Notifications

jobs:
  release-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post Release Notification
        uses: bythope/discord-webhook-messages@v1.0.0
        with:
          webhookUrl: ${{ secrets.DISCORD_BYTECH_WEBHOOK_URL }}
          handler: 'release'