name: Discord Commits
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Run Discord Webhook
      uses: Mist3r-Robot/classic-discord-webhook@v1.0.0
      with:
        id: ${{ secrets.BYTECH_DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.BYTECH_DISCORD_WEBHOOK_TOKEN }}
