name: Publish
on:
  push:
    tags: 
      - v*
  
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Bytech/Bythope.Bytech.csproj
          PACKAGE_NAME: Bytech
          TAG_COMMIT: false
          VERSION_FILE_PATH: Bytech/Bythope.Bytech.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY }}
          
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
        
      - name: Discord Notification
        id: "send-to-discord-main"
        uses: "hugoalh/GitHubAction.SendToDiscord@v2.0.0"
        with:
          webhook_id: "${{secrets.BYTECH_DISCORD_WEBHOOK_ID}}"
          webhook_token: "${{secrets.BYTECH_DISCORD_WEBHOOK_TOKEN}}"
          message_usetexttospeech: "false"
          message_embed_colour: "0,188,212"
          message_embed_title: "${{ steps.tagName.outputs.tag }} version is released!"
          message_embed_titleurl: "https://bythope.github.io/bytech/#/changelog"
          message_embed_description: "I'm happy to announce my new version. Check the updates"
          message_embed_footertext: ${{ steps.tagName.outputs.tag }}
          variable_prefix: "%"
          variable_suffix: "%"
          variable_join: "."
