name: Publish
on:
  release:
    types: [published]
  
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: publish
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Bytech/Bythope.Bytech.csproj
          PACKAGE_NAME: Bytech
          TAG_COMMIT: false
          VERSION_FILE_PATH: Bytech/Bythope.Bytech.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY }}
